# Generated by Django 4.0.3 on 2022-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_question_prize_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(),
        ),
    ]
