# Generated by Django 4.0.3 on 2022-04-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0003_alter_question_prize_alter_question_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='passed',
        ),
    ]
