# Generated by Django 4.0.3 on 2022-04-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0003_alter_profile_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_app.task', unique=True),
        ),
    ]
