# Generated by Django 4.0.3 on 2022-04-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0004_remove_task_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='ttt', upload_to='images/'),
            preserve_default=False,
        ),
    ]
