# Generated by Django 4.0.3 on 2022-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0005_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='question', upload_to='images/questions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(upload_to='images/tasks'),
        ),
    ]
